package:
  name: nexusformat
  version: "0.6.1"

source:
  git_url: https://github.com/nexpy/nexusformat.git
  git_tag: v0.6.1

build:
  entry_points:
    - nxstack = nexusformat.scripts.nxstack:main
    - nxduplicate = nexusformat.scripts.nxduplicate:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - h5py
    - ipython

  run:
    - python
    - numpy
    - h5py

test:
  commands:
    - nexusformat --version

about:
  home: http://nexpy.github.io/nexusformat/
  license: BSD License
  summary: 'nexusformat: Python API to access NeXus data'
