package:
  name: nexusformat
  version: "0.5.0"

source:
  git_url: https://github.com/nexpy/nexusformat.git
  git_tag: v0.5.0

build:
  entry_points:
    - nxstack = nexusformat.scripts.nxstack:main
    - nxduplicate = nexusformat.scripts.nxduplicate:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0
    - h5py
    - ipython

  run:
    - python
    - numpy >=1.6.0
    - h5py

test:
  imports:
    - nexusformat
    - nexusformat.nexus

about:
  home: http://nexpy.github.io/nexusformat/
  license: BSD License
  summary: 'nexusformat: Python API to access NeXus data'
