package:
  name: nexusformat
  version: "0.2.2"

source:
  git_url: https://github.com/nexpy/nexusformat.git
  git_tag: v0.2.2

build:
  entry_points:
    - nxstack = nexusformat.scripts.nxstack:main
    - nxstartserver = nexusformat.pyro.start_server:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0
    - h5py

  run:
    - python
    - numpy >=1.6.0
    - h5py

test:
  imports:
    - nexusformat
    - nexusformat.nexus

about:
  home: http://nexpy.github.io/nexusformat/
  license: BSD License
  summary: 'nexusformat: Python API to access NeXus data'
